spring.datasource.url=jdbc:sqlserver://192.168.1.187;databaseName=ticket_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sipl@123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# JPA configurations
spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
# App Information
app.version=@version@
app.name=@name@
app.description=@description@
app.build.timestamp=@timestamp@
server.servlet.context-path=/ticket-app
scheduler.orderAssignment.revoke.delay=120000
notification.service.url=https://ion.app.surajinformatics.in/vcms-notification-service/api/v1/notification
email.request.id=T0005
send.otp.template.id=4
sender.mail=alerts@surajinformatics.in

faqFilePath=/data/faq-support-documents

#Apk download file path
filePath=/opt/tomcat/latest/android-apk/apk/
#dms.service.url = http://192.168.1.195:8080/dms-service/
dms.service.url = https://ticket.app.surajinformatics.in/dms-service/api/v1/documents

spring.cache.type=none
spring.redis.host=192.168.1.89
spring.redis.port=6379
spring.redis.password=Sipl@123
spring.redis.timeout=60000
spring.redis.auth.enabled=true
spring.cache.redis.key-prefix=ticket-app::
spring.cache.redis.use-key-prefix=true
cached.tag.expiry.timeout=60


#Templates
transaction_cancellation_initiated=8
transaction_cancellation_req_rejected=9
transaction_cancellation_req_approved=10
transaction_cancellation_req_next_stage=13

#Masters
gate.master.id=1
yard.master.id=2
transporter.master.id=2

transaction.report.csv.path=/opt/tomcat/latest/reports/
save.epod.files=/opt/tomcat/latest/epod

server.max-http-header-size=64KB
save.customer.api.url=https://ion.app.surajinformatics.in/rbac-vcms/api/v1/user/save/customer-user
BaseFilePath = /opt/tomcat/webapps/wms/docs
TIcketFilePath=C:/opt/tomcat/webapps/wms
#TIcketFilePath=/opt/tomcat/webapps/wms

spring.datasource.hikari.keepalive-time=240000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.auto-commit=true



